#
#

version: "3.9"
services:
  projects:
    image: wordpress-projects:${PROJECTS_TAG}
    build: ./wordpress-projects/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
    name: wordpress_${WORDPRESS_TAG}_data
  
